image overlay
location-tips/location-tips-nx pull request #116
Opened 2024-08-19 19:15 UTC by vvruspat

2024-08-19 19:43 UTC, Glaicer commented on packages/frontend/src/components/ImageOverlay/ImageOverlay.module.css
> +  background-color: color-mix(
ты учил меня, что переменные надо выносить в :root[data-theme] и :root[data-platform] файла *.vars.css))

2024-08-19 19:46 UTC, Glaicer requested changes
для единообразия кода стоит внести переменные из ImageOverlay.module.css в блоки :root[data-theme] и :root[data-platform] ImageOverlay.vars.css

2024-08-20 06:12 UTC, vvruspat commented on packages/frontend/src/components/ImageOverlay/ImageOverlay.module.css
> +  background-color: color-mix(
Ты прав )

2024-08-20 07:27 UTC, Glaicer approved these changes

2024-08-20 08:18 UTC, merged